services:
  api:
    container_name: api
    depends_on:
      - postgres
      - redis
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init-unaccent.sql:/docker-entrypoint-initdb.d/init-unaccent.sql
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=vi
      - TZ=posix/Asia/Ho_Chi_Minh
    restart: unless-stopped
    networks:
      - network

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}', '--appendonly', 'yes']
    ports:
      - '6379:${REDIS_PORT}'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgresql_data:
  redis_data:
